import { DowntimeLog, DowntimeLogStats } from '../types/downtime-log.types';

export const mockDowntimeLogs: DowntimeLog[] = [
  {
    id: '1',
    machineId: '1',
    machineName: 'LI-43-OM-910',
    startTime: new Date(Date.now() - 1000 * 60 * 45),
    endTime: new Date(Date.now() - 1000 * 60 * 15),
    duration: 30,
    reason: 'Machine Breakdown',
    reasonCode: 'UNP-001',
    reasonCategory: 'unplanned',
    operator: 'Mike Johnson',
    shift: 'A',
    remarks: 'Motor overheating issue',
    status: 'resolved',
    createdAt: new Date(Date.now() - 1000 * 60 * 45),
    updatedAt: new Date(Date.now() - 1000 * 60 * 15),
  },
  {
    id: '2',
    machineId: '2',
    machineName: 'LI-44-OM-920',
    startTime: new Date(Date.now() - 1000 * 60 * 120),
    endTime: new Date(Date.now() - 1000 * 60 * 90),
    duration: 30,
    reason: 'Scheduled Maintenance',
    reasonCode: 'PLN-001',
    reasonCategory: 'planned',
    operator: 'Sarah Smith',
    shift: 'A',
    remarks: 'Routine maintenance completed',
    status: 'resolved',
    createdAt: new Date(Date.now() - 1000 * 60 * 120),
    updatedAt: new Date(Date.now() - 1000 * 60 * 90),
  },
  {
    id: '3',
    machineId: '3',
    machineName: 'LI-45-OM-930',
    startTime: new Date(Date.now() - 1000 * 60 * 10),
    endTime: undefined,
    duration: undefined,
    reason: 'Material Shortage',
    reasonCode: 'UNP-003',
    reasonCategory: 'unplanned',
    operator: 'Tom Wilson',
    shift: 'A',
    remarks: 'Waiting for raw materials',
    status: 'active',
    createdAt: new Date(Date.now() - 1000 * 60 * 10),
    updatedAt: new Date(Date.now() - 1000 * 60 * 10),
  },
  {
    id: '4',
    machineId: '1',
    machineName: 'LI-43-OM-910',
    startTime: new Date(Date.now() - 1000 * 60 * 60 * 3),
    endTime: new Date(Date.now() - 1000 * 60 * 60 * 2.5),
    duration: 30,
    reason: 'Lunch Break',
    reasonCode: 'BRK-001',
    reasonCategory: 'break',
    operator: 'Mike Johnson',
    shift: 'A',
    remarks: '',
    status: 'resolved',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 3),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 2.5),
  },
  {
    id: '5',
    machineId: '2',
    machineName: 'LI-44-OM-920',
    startTime: new Date(Date.now() - 1000 * 60 * 60 * 5),
    endTime: new Date(Date.now() - 1000 * 60 * 60 * 4),
    duration: 60,
    reason: 'Machine Setup',
    reasonCode: 'SET-001',
    reasonCategory: 'setup',
    operator: 'Sarah Smith',
    shift: 'B',
    remarks: 'Setting up for new product',
    status: 'resolved',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 5),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 4),
  },
  {
    id: '6',
    machineId: '3',
    machineName: 'LI-45-OM-930',
    startTime: new Date(Date.now() - 1000 * 60 * 60 * 6),
    endTime: new Date(Date.now() - 1000 * 60 * 60 * 5.5),
    duration: 30,
    reason: 'Quality Inspection',
    reasonCode: 'QTY-001',
    reasonCategory: 'quality',
    operator: 'Emma Davis',
    shift: 'B',
    remarks: 'Quality check passed',
    status: 'resolved',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 6),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 5.5),
  },
];

export const mockDowntimeStats: DowntimeLogStats = {
  totalDowntime: 210,
  totalEvents: 6,
  activeEvents: 1,
  averageDuration: 35,
  mostCommonReason: 'Machine Breakdown',
  mostCommonReasonCount: 2,
  machinesAffected: 3,
  availability: 87.5,
  mtbf: 180,
  mttr: 45,
  oeeImpact: 12.5,
  downtimeByCategory: [
    { category: 'Unplanned', duration: 60, count: 2 },
    { category: 'Planned', duration: 30, count: 1 },
    { category: 'Break', duration: 30, count: 1 },
    { category: 'Setup', duration: 60, count: 1 },
    { category: 'Quality', duration: 30, count: 1 },
  ],
  downtimeByMachine: [
    { machineId: '1', machineName: 'LI-43-OM-910', duration: 60, count: 2 },
    { machineId: '2', machineName: 'LI-44-OM-920', duration: 90, count: 2 },
    { machineId: '3', machineName: 'LI-45-OM-930', duration: 60, count: 2 },
  ],
};