import { Machine, Product, Operator, Plant, Shift, ReasonCode } from '../types/master-data.types';

export const mockMachines: Machine[] = [
  {
    id: '1',
    code: 'MCH-001',
    name: 'LI-43-OM-910',
    description: 'Automated assembly line',
    isActive: true,
    type: 'production',
    plantId: '1',
    plantName: 'Plant A',
    model: 'XL-9000',
    serialNumber: 'SN-2024-001',
    installationDate: new Date('2024-01-15'),
    lastMaintenanceDate: new Date('2024-06-15'),
    status: 'active',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-06-15'),
  },
  {
    id: '2',
    code: 'MCH-002',
    name: 'LI-44-OM-920',
    description: 'Packaging machine',
    isActive: true,
    type: 'packaging',
    plantId: '1',
    plantName: 'Plant A',
    model: 'PK-5000',
    serialNumber: 'SN-2024-002',
    installationDate: new Date('2024-02-01'),
    status: 'active',
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-05-20'),
  },
  {
    id: '3',
    code: 'MCH-003',
    name: 'LI-45-OM-930',
    description: 'Quality inspection station',
    isActive: false,
    type: 'quality',
    plantId: '2',
    plantName: 'Plant B',
    model: 'QC-2000',
    serialNumber: 'SN-2024-003',
    installationDate: new Date('2024-03-01'),
    status: 'maintenance',
    createdAt: new Date('2024-03-01'),
    updatedAt: new Date('2024-06-01'),
  },
];

export const mockProducts: Product[] = [
  {
    id: '1',
    code: 'PRD-001',
    name: 'Widget A',
    description: 'Standard widget for industrial use',
    isActive: true,
    category: 'finished',
    unit: 'pcs',
    weight: 2.5,
    dimensions: '10x5x3 cm',
    material: 'Aluminum',
    supplierId: '1',
    supplierName: 'Supplier Corp',
    reorderLevel: 100,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-06-01'),
  },
  {
    id: '2',
    code: 'PRD-002',
    name: 'Widget B',
    description: 'Heavy-duty widget',
    isActive: true,
    category: 'finished',
    unit: 'pcs',
    weight: 5.0,
    dimensions: '15x8x4 cm',
    material: 'Steel',
    supplierId: '2',
    supplierName: 'Metal Works Inc',
    reorderLevel: 50,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-05-15'),
  },
  {
    id: '3',
    code: 'PRD-003',
    name: 'Widget C',
    description: 'Precision widget',
    isActive: false,
    category: 'wip',
    unit: 'pcs',
    weight: 1.8,
    dimensions: '8x4x2 cm',
    material: 'Plastic',
    supplierId: '3',
    supplierName: 'Plastics Ltd',
    reorderLevel: 200,
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-04-01'),
  },
];

export const mockOperators: Operator[] = [
  {
    id: '1',
    code: 'OP-001',
    name: 'Mike Johnson',
    description: 'Senior machine operator',
    isActive: true,
    employeeId: 'EMP-001',
    department: 'production',
    position: 'Senior Operator',
    shiftPreference: 'A',
    skills: ['Machine Operation', 'Quality Control', 'Maintenance'],
    certifications: ['ISO 9001', 'Safety Certification'],
    contactNumber: '+1-555-0101',
    email: 'mike.j@company.com',
    joinDate: new Date('2022-01-15'),
    createdAt: new Date('2022-01-15'),
    updatedAt: new Date('2024-05-20'),
  },
  {
    id: '2',
    code: 'OP-002',
    name: 'Sarah Smith',
    description: 'Quality control specialist',
    isActive: true,
    employeeId: 'EMP-002',
    department: 'quality',
    position: 'Quality Specialist',
    shiftPreference: 'B',
    skills: ['Quality Inspection', 'Testing', 'Documentation'],
    certifications: ['Six Sigma Green Belt', 'Quality Management'],
    contactNumber: '+1-555-0102',
    email: 'sarah.s@company.com',
    joinDate: new Date('2022-03-01'),
    createdAt: new Date('2022-03-01'),
    updatedAt: new Date('2024-05-25'),
  },
  {
    id: '3',
    code: 'OP-003',
    name: 'Tom Wilson',
    description: 'Maintenance technician',
    isActive: false,
    employeeId: 'EMP-003',
    department: 'maintenance',
    position: 'Senior Technician',
    shiftPreference: 'C',
    skills: ['Electrical', 'Mechanical', 'PLC Programming'],
    certifications: ['Electrical License', 'Safety Certification'],
    contactNumber: '+1-555-0103',
    email: 'tom.w@company.com',
    joinDate: new Date('2021-06-01'),
    createdAt: new Date('2021-06-01'),
    updatedAt: new Date('2024-03-01'),
  },
];

export const mockPlants: Plant[] = [
  {
    id: '1',
    code: 'PLT-001',
    name: 'Plant A',
    description: 'Main manufacturing facility',
    isActive: true,
    location: 'Industrial Zone 1',
    address: '123 Factory Road',
    city: 'Metropolis',
    state: 'CA',
    country: 'USA',
    phone: '+1-555-0001',
    email: 'plant.a@company.com',
    manager: 'John Manager',
    timezone: 'America/Los_Angeles',
    createdAt: new Date('2020-01-01'),
    updatedAt: new Date('2024-06-01'),
  },
  {
    id: '2',
    code: 'PLT-002',
    name: 'Plant B',
    description: 'Secondary manufacturing facility',
    isActive: true,
    location: 'Industrial Zone 2',
    address: '456 Industrial Ave',
    city: 'Metropolis',
    state: 'CA',
    country: 'USA',
    phone: '+1-555-0002',
    email: 'plant.b@company.com',
    manager: 'Jane Supervisor',
    timezone: 'America/Los_Angeles',
    createdAt: new Date('2020-06-01'),
    updatedAt: new Date('2024-05-15'),
  },
  {
    id: '3',
    code: 'PLT-003',
    name: 'Plant C',
    description: 'Warehouse and distribution',
    isActive: false,
    location: 'Industrial Zone 3',
    address: '789 Distribution Blvd',
    city: 'Metropolis',
    state: 'CA',
    country: 'USA',
    phone: '+1-555-0003',
    email: 'plant.c@company.com',
    manager: 'Bob Logistician',
    timezone: 'America/Los_Angeles',
    createdAt: new Date('2021-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
];

export const mockShifts: Shift[] = [
  {
    id: '1',
    code: 'A',
    name: 'Morning Shift',
    description: '6:00 AM - 2:00 PM',
    isActive: true,
    timeStart: '06:00',
    timeEnd: '14:00',
    supervisors: ['John Manager', 'Jane Supervisor'],
    maxOperators: 20,
    createdAt: new Date('2020-01-01'),
    updatedAt: new Date('2024-06-01'),
  },
  {
    id: '2',
    code: 'B',
    name: 'Afternoon Shift',
    description: '2:00 PM - 10:00 PM',
    isActive: true,
    timeStart: '14:00',
    timeEnd: '22:00',
    supervisors: ['Mike Supervisor', 'Sarah Lead'],
    maxOperators: 18,
    createdAt: new Date('2020-01-01'),
    updatedAt: new Date('2024-05-20'),
  },
  {
    id: '3',
    code: 'C',
    name: 'Night Shift',
    description: '10:00 PM - 6:00 AM',
    isActive: false,
    timeStart: '22:00',
    timeEnd: '06:00',
    supervisors: ['Tom Night Manager'],
    maxOperators: 15,
    createdAt: new Date('2020-01-01'),
    updatedAt: new Date('2024-03-01'),
  },
];

export const mockReasonCodes: ReasonCode[] = [
  {
    id: '1',
    code: 'BRK-001',
    name: 'Break',
    description: 'Scheduled break time',
    isActive: true,
    category: 'downtime',
    priority: 'low',
    requiresApproval: false,
    createdAt: new Date('2020-01-01'),
    updatedAt: new Date('2024-06-01'),
  },
  {
    id: '2',
    code: 'MNT-001',
    name: 'Maintenance',
    description: 'Preventive or emergency maintenance',
    isActive: true,
    category: 'downtime',
    priority: 'high',
    requiresApproval: true,
    responsibleDepartment: 'maintenance',
    createdAt: new Date('2020-01-01'),
    updatedAt: new Date('2024-05-15'),
  },
  {
    id: '3',
    code: 'QTY-001',
    name: 'Quality Issue',
    description: 'Quality inspection failure',
    isActive: true,
    category: 'quality',
    priority: 'critical',
    requiresApproval: true,
    responsibleDepartment: 'quality',
    createdAt: new Date('2020-01-01'),
    updatedAt: new Date('2024-05-20'),
  },
  {
    id: '4',
    code: 'REJ-001',
    name: 'Rejection',
    description: 'Product rejection due to defects',
    isActive: true,
    category: 'rejection',
    priority: 'high',
    requiresApproval: true,
    responsibleDepartment: 'quality',
    createdAt: new Date('2020-01-01'),
    updatedAt: new Date('2024-05-10'),
  },
  {
    id: '5',
    code: 'SCR-001',
    name: 'Scrap',
    description: 'Product scrap due to defects',
    isActive: false,
    category: 'scrap',
    priority: 'medium',
    requiresApproval: true,
    responsibleDepartment: 'production',
    createdAt: new Date('2020-01-01'),
    updatedAt: new Date('2024-04-01'),
  },
];

export const getMockData = (type: string) => {
  switch (type) {
    case 'machines': return mockMachines;
    case 'products': return mockProducts;
    case 'operators': return mockOperators;
    case 'plants': return mockPlants;
    case 'shifts': return mockShifts;
    case 'reason-codes': return mockReasonCodes;
    default: return [];
  }
};